### ISSUE TITLE
关于 管理页面

### ISSUE THREAD

**Issue by 9ouhao** [flyhigher139/OctBlog#10]
在 /admin 界面中可以创建新的Wechat 和 Page 这两个东西的作用有点不懂这两个界面的内容和 new post界面的内容一致呀。而且在OctBlog db中只有post这个collection，他们的具体分别只在post_type， 这是什么用意呀？
http://localhost:5000/admin/new-wechat/
http://localhost:5000/admin/new-page/

**Comment by flyhigher139** [comment]
wechat 是微信，这个是原来出于我个人需求写的，你可以不用关心
page 是每个博客系统的基本元素之一，你可以去看看我博客的右上角，page会显示在那里
