### ISSUE TITLE
博客上传图片的问题

### ISSUE THREAD

**Issue by huangtao00** [flyhigher139/OctBlog#14]
感谢兄弟的开源博客，目前我改了下web ui，差不快改完了，三个问题请教一下：
１：老哥blog上线是用的阿云的哪个套餐啊？准备上线部署了，没找到合适的云主机
２：图片上传的url是别外生成的吗？flask-markdown好像没有这个功能，哥们有考虑在博客中实现直接上传图片文件吗？
３：域名绑定后，备案了吗？

先买了vultr一个月的套餐，域名还没有买绑定。
http://45.77.173.62/

**Comment by flyhigher139** [comment]
@huangtao00 

1. 阿里云上你找不到合适的，用vultr没问题，而且vultr上域名也不需要备案
2. 图片是外链的，我这里暂时没做直接上传图片并托管
3. 国内的云，是要备案的

**Comment by huangtao00** [comment]
@flyhigher139 国外的速度还是有点慢，国内要备案也是麻烦。再次谢谢了！我还是先上线了，后面再慢慢改进博客的ui和功能吧！有问题我再来请教老兄。

**Comment by huangtao00** [comment]
博客上线：http://www.meyoublog.com/，再次感谢哥们的这个开源项目。

**Comment by huangtao00** [comment]
把本地图片上传的问题解决了，引入了editor.md，http://www.meyoublog.com/posts/editormd-blog/

**Comment by flyhigher139** [comment]
@huangtao00 这个有空的时候我也可以拿来借鉴一下 👍
