### ISSUE TITLE
Deploy OctBlog by debian8 mod_wsgi

### ISSUE THREAD

**Issue by renmu123** [flyhigher139/OctBlog#15]
# 环境
linux：debian 8
python：3.6

# 配置基础环境
1. 更新软件源
    `sudo apt-get update`
2. 安装apache2
    `sudo apt-get install apache2`
3. 安装mod-wsgi
    `sudo apt-get install libapache2-mod-wsgi-py3`
    到这里基础环境的配置就完毕了

# 创建wsgi.py

Apache 使用 .wsgi 来启动 Flask 程序。使用以下命令打开 /var/www/projectapp 目录，创建一个 flaskapp.wsgi 文件。

        cd /var/www/projectapp
        sudo nano flaskapp.wsgi
        # 增加如下内容
        #!/usr/bin/python
        import sys
        import logging
        activate_this = '/var/www/OctBlog/venv/bin/activate_this.py'  # 这是虚拟环境路径
        with open(activate_this) as file_:                            # py3的调用
            exec(file_.read(), dict(__file__=activate_this))
        logging.basicConfig(stream=sys.stderr)
        sys.path.insert(0,"/var/www/projectapp/")  #你app的目录
        from OctBlog import app 
        application = app

# Apache2配置文件
`sudo nano /etc/apache2/sites-available/yoursite.conf`

    <VirtualHost *:80>
        ServerName www.xxx.com 
        #ServerAlias xxx.com
        #ServerAdmin xxxx@example.com 
        # 存放用户上传图片等文件的位置，注意去掉#号
        # Alias /media/ /var/www/ProjectName/media/ 
        # 静态文件(js/css/images)的存放位置
        Alias /static/ /var/www/OctBlog/app/static/                
        # 允许通过网络获取static的内容
        <Directory /var/www/OctBlog/app/static/>                  
            Require all granted
        </Directory>
        # wsgi文件
        WSGIScriptAlias / /var/www/OctBlog/app/flaskapp.wsgi  
    </VirtualHost>

应用配置文件`sudo a2ensite projectapp`

重启apache2`sudo service apache2 restart`

**！！！遇到问题查看errorlog，/var/log/apache2/error.log**
    
[Here is my blog](http://www.irenmu.com/posts/flask-debian/)

**Comment by flyhigher139** [comment]
我推荐用nginx + gunicorn 来部署

我最近还写了一篇对应的博客，不知是否有帮助：  [Flask 应用如何部署](https://blog.igevin.info/posts/how-to-deploy-flask-apps/)
