### ISSUE TITLE
Why I can't update my config.py?

### ISSUE THREAD

**Issue by cicada-lewis** [flyhigher139/OctBlog#16]
I have deployed the blog on my service,and I want change the homepage of my blog and I have changed environments variables in config.py,but the homepage of my blog is still the default page,How to change the ? thx.

**Comment by flyhigher139** [comment]
You can only change the background image of the homepage

**Comment by cicada-lewis** [comment]
emmm,no, I do not want to change the background, you must misunderstand my words. 我们还是说中文吧,我的`.env`这个文件并不起作用,无论我怎么设置任何值都不会改变,于是我又尝试了修改config.py文件,修改了所有的默认参数,也是没有用,这个名字在我看来不是那么重要,主要是如果`.env`参数不生效,那allow_su_creation就一直是true,就很危险,另外`.env`的name应该就是blog的name吧,不生效就没法显示在主页上

**Comment by cicada-lewis** [comment]
还有就是萌新小小的建议,大佬的代码都没什么注释啊~~教练,我想学python啊

**Comment by flyhigher139** [comment]
@Catelemmon 你是用docker起的服务么？

**Comment by cicada-lewis** [comment]
对的, 确实是用docker起的

**Comment by flyhigher139** [comment]
@Catelemmon 修改了env文件的话，你进到容器里去，打印一下环境变量，看看你的配置是否生效
