### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by dxh007** [flyhigher139/OctBlog#17]
你好，首先非常感谢你的分享。我想把你的代码部署到生产坏境去，采用nginx + gunicorn+centos,请问有详细的部署教程吗？我是Python新手，弄了两天也没有成功。需要你的帮助，万分感谢！

**Comment by flyhigher139** [comment]
@dxh007 不知我这篇文章，对你有没有帮助： [Flask 应用如何部署](https://blog.igevin.info/posts/how-to-deploy-flask-apps/)
