### ISSUE TITLE
能不能提供一个文章置顶的功能

### ISSUE THREAD

**Issue by laolai** [flyhigher139/OctBlog#3]
想把某篇POST置顶在最上方

**Comment by flyhigher139** [comment]
@laolai 可以，增加一个权重字段，文章按权重排序，你提出的文章置顶，即置顶文章的权重比默认权重高

**Comment by laolai** [comment]
嗯嗯我考虑自己手动改一下，感谢

**Comment by flyhigher139** [comment]
@laolai 我在commit [608df90d56462cdbedc60c3d9211c3ec0cedaaf0](https://github.com/flyhigher139/OctBlog/commit/608df90d56462cdbedc60c3d9211c3ec0cedaaf0)中添加了文章的权重，也在readme 中添加了相应说明，你可以直接查看`dev分支`的代码

**Comment by flyhigher139** [comment]
在commit [475032477fff25403e7f877f164d44be9c973f7e](https://github.com/flyhigher139/OctBlog/commit/475032477fff25403e7f877f164d44be9c973f7e)中，对权重功能做了向后兼容
