### ISSUE TITLE
请问发表的文章怎么展示在首页

### ISSUE THREAD

**Issue by ZXXACC** [flyhigher139/OctBlog#6]
我post一篇文章之后首页右上角显示出来这篇文章的slug但是首页不点进去就看不到他

**Comment by ZXXACC** [comment]
啊，sorry是post我发成了pages_(:з」∠)_怪不得。
还有一个想请教一下wechat分类是什么~

**Comment by flyhigher139** [comment]
@ZXXACC wechat 就是微信啊，不过我考虑以后把这个入口删了

**Comment by ZXXACC** [comment]
@flyhigher139 原来真是是微信哈哈哈这个入口确实不太用不着~博客很棒赞 ！
